### ISSUE TITLE
Add endpoint exposing data write (or all) fee details

### ISSUE THREAD

**Issue by cptartur** [stellar/soroban-rpc#159] opened 2024-04-24 14:52 UTC
### What problem does your feature solve?

Currently, it's not easily possible (or not possible at all) to get the fees breakdown for writing data to the ledger. 

### What would you like to see?

Add a new endpoint which exposes the current fee details. I propose that for future proofing it exposes all fees, even the ones that do not change dynamically i.e. all fees included in this documentation page: 

https://developers.stellar.org/docs/reference/resource-limits-fees#resource-fees

Additionally, values like minimum TTL for entries could be provided in the endpoint output as well.

### What alternatives are there?

A minimal viable solution would just be an endpoint that provides the fee of writing to the ledger, without the data on other fees.

**Comment by cptartur** [comment] 2024-04-24 14:54
What we could consider is also providing the details on fees paid for the sent transaction. This would be a nice to have feature for reference. However, only implementing this without creating a separate endpoint for fees would not resolve the issue.

**Comment by mollykarcher** [comment] 2024-05-09 13:58
@cptartur thanks for reporting! I'm going to close this as a duplicate of #114, but please comment over there and/or reopen if you think that solution won't suit your needs.

**Closed by mollykarcher** 2024-05-09 13:58 UTC
