### ISSUE TITLE
Feature: Expose a `getLedgers` endpoint

### ISSUE THREAD

**Issue by mootz12** [stellar/soroban-rpc#109] opened 2024-03-20 14:38 UTC
### What problem does your feature solve?

Get ledger is useful for applications to get information about a past ledger from the sequence number, like what time the ledger was closed at.

Currently, applications must integrate horizon as well if they wish to translate any past sequence number to a timestamp.

### What would you like to see?

An endpoint on the RPC like: https://developers.stellar.org/network/horizon/resources/retrieve-a-ledger

### What alternatives are there?

Use Horizon and the RPC in the same application. This works, but IIRC there was a push to avoid having dApps depend on both Horizon and the RPC. If this is not correct - please feel free to close this feature request.

**Comment by mollykarcher** [comment] 2024-05-09 13:56
Closing this as a duplicate of #111

**Closed by mollykarcher** 2024-05-09 13:56 UTC
